# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFrame, QHBoxLayout, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1914, 1165)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pre_video = QLabel(self.centralwidget)
        self.pre_video.setObjectName(u"pre_video")
        self.pre_video.setGeometry(QRect(10, 190, 911, 921))
        self.pre_video.setAlignment(Qt.AlignCenter)
        self.run_button = QPushButton(self.centralwidget)
        self.run_button.setObjectName(u"run_button")
        self.run_button.setGeometry(QRect(350, 80, 81, 41))
        self.run_button.setCheckable(True)
        self.status_bar = QLabel(self.centralwidget)
        self.status_bar.setObjectName(u"status_bar")
        self.status_bar.setGeometry(QRect(20, 1130, 791, 31))
        self.status_bar.setStyleSheet(u"font: 700 11pt \"Microsoft YaHei UI\";")
        self.src_file_button = QPushButton(self.centralwidget)
        self.src_file_button.setObjectName(u"src_file_button")
        self.src_file_button.setGeometry(QRect(790, 110, 71, 41))
        self.src_cam_button = QPushButton(self.centralwidget)
        self.src_cam_button.setObjectName(u"src_cam_button")
        self.src_cam_button.setGeometry(QRect(890, 110, 71, 41))
        self.src_rtsp_button = QPushButton(self.centralwidget)
        self.src_rtsp_button.setObjectName(u"src_rtsp_button")
        self.src_rtsp_button.setGeometry(QRect(990, 110, 71, 41))
        self.close_button = QPushButton(self.centralwidget)
        self.close_button.setObjectName(u"close_button")
        self.close_button.setGeometry(QRect(1810, 0, 101, 41))
        self.stop_button = QPushButton(self.centralwidget)
        self.stop_button.setObjectName(u"stop_button")
        self.stop_button.setGeometry(QRect(440, 80, 81, 41))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 180, 1891, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(920, 190, 20, 931))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.res_video = QLabel(self.centralwidget)
        self.res_video.setObjectName(u"res_video")
        self.res_video.setGeometry(QRect(940, 190, 961, 921))
        self.res_video.setAlignment(Qt.AlignCenter)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 1116, 1891, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(330, 140, 221, 24))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.layoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setStyleSheet(u"font: 700 12pt \"Microsoft YaHei UI\";")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout.addWidget(self.label_2)

        self.model_box = QComboBox(self.layoutWidget)
        self.model_box.setObjectName(u"model_box")

        self.horizontalLayout.addWidget(self.model_box)

        self.layoutWidget1 = QWidget(self.centralwidget)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(780, 20, 301, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.save_res_button = QCheckBox(self.layoutWidget1)
        self.save_res_button.setObjectName(u"save_res_button")
        self.save_res_button.setStyleSheet(u"font: 700 11pt \"Microsoft YaHei UI\";")

        self.horizontalLayout_2.addWidget(self.save_res_button)

        self.save_txt_button = QCheckBox(self.layoutWidget1)
        self.save_txt_button.setObjectName(u"save_txt_button")
        self.save_txt_button.setStyleSheet(u"font: 700 11pt \"Microsoft YaHei UI\";")

        self.horizontalLayout_2.addWidget(self.save_txt_button)

        self.fps_label = QLabel(self.centralwidget)
        self.fps_label.setObjectName(u"fps_label")
        self.fps_label.setGeometry(QRect(1640, 80, 81, 41))
        self.fps_label.setStyleSheet(u"font: 700 10pt \"Microsoft YaHei UI\";")
        self.fps_label.setAlignment(Qt.AlignCenter)
        self.iou_spinbox = QDoubleSpinBox(self.centralwidget)
        self.iou_spinbox.setObjectName(u"iou_spinbox")
        self.iou_spinbox.setGeometry(QRect(1320, 40, 62, 22))
        self.iou_spinbox.setMinimum(0.010000000000000)
        self.iou_spinbox.setMaximum(1.000000000000000)
        self.iou_spinbox.setSingleStep(0.050000000000000)
        self.iou_spinbox.setValue(0.450000000000000)
        self.conf_spinbox = QDoubleSpinBox(self.centralwidget)
        self.conf_spinbox.setObjectName(u"conf_spinbox")
        self.conf_spinbox.setGeometry(QRect(1320, 90, 62, 22))
        self.conf_spinbox.setMinimum(0.010000000000000)
        self.conf_spinbox.setMaximum(1.000000000000000)
        self.conf_spinbox.setSingleStep(0.050000000000000)
        self.conf_spinbox.setValue(0.250000000000000)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1200, 40, 107, 22))
        self.label_3.setStyleSheet(u"font: 700 12pt \"Microsoft YaHei UI\";")
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1200, 90, 107, 22))
        self.label_4.setStyleSheet(u"font: 700 12pt \"Microsoft YaHei UI\";")
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.iou_slider = QSlider(self.centralwidget)
        self.iou_slider.setObjectName(u"iou_slider")
        self.iou_slider.setGeometry(QRect(1400, 40, 160, 22))
        self.iou_slider.setMinimum(1)
        self.iou_slider.setMaximum(100)
        self.iou_slider.setValue(45)
        self.iou_slider.setOrientation(Qt.Horizontal)
        self.conf_slider = QSlider(self.centralwidget)
        self.conf_slider.setObjectName(u"conf_slider")
        self.conf_slider.setGeometry(QRect(1400, 90, 160, 22))
        self.conf_slider.setMinimum(1)
        self.conf_slider.setMaximum(100)
        self.conf_slider.setValue(25)
        self.conf_slider.setOrientation(Qt.Horizontal)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1200, 140, 107, 22))
        self.label_5.setStyleSheet(u"font: 700 12pt \"Microsoft YaHei UI\";")
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.speed_slider = QSlider(self.centralwidget)
        self.speed_slider.setObjectName(u"speed_slider")
        self.speed_slider.setGeometry(QRect(1400, 140, 160, 22))
        self.speed_slider.setMaximum(50)
        self.speed_slider.setValue(10)
        self.speed_slider.setOrientation(Qt.Horizontal)
        self.speed_spinbox = QSpinBox(self.centralwidget)
        self.speed_spinbox.setObjectName(u"speed_spinbox")
        self.speed_spinbox.setGeometry(QRect(1320, 140, 61, 22))
        self.speed_spinbox.setMaximum(50)
        self.speed_spinbox.setValue(10)
        self.result_label = QListWidget(self.centralwidget)
        self.result_label.setObjectName(u"result_label")
        self.result_label.setGeometry(QRect(50, 10, 211, 161))
        self.result_label.setStyleSheet(u"font: 700 10pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.progress_bar = QProgressBar(self.centralwidget)
        self.progress_bar.setObjectName(u"progress_bar")
        self.progress_bar.setGeometry(QRect(1060, 1140, 841, 16))
        self.progress_bar.setMaximum(1000)
        self.progress_bar.setValue(0)
        self.progress_bar.setTextVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"YOLOv8-Detector", None))
        self.pre_video.setText("")
        self.run_button.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.status_bar.setText(QCoreApplication.translate("MainWindow", u"Welcome!", None))
        self.src_file_button.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6587\u4ef6", None))
        self.src_cam_button.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6444\u50cf\u5934", None))
        self.src_rtsp_button.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u7f51\u7edc\u6e90", None))
        self.close_button.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed", None))
        self.stop_button.setText(QCoreApplication.translate("MainWindow", u"\u7ec8\u6b62", None))
        self.res_video.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u9009\u62e9\uff1a", None))
        self.save_res_button.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u68c0\u6d4b\u7ed3\u679c", None))
        self.save_txt_button.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6807\u7b7e", None))
        self.fps_label.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"IOU:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Conf:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u64ad\u653e\u5ef6\u65f6(ms):", None))
    # retranslateUi


